from __future__ import annotations

import argparse
import json
import textwrap
from pathlib import Path


def render(cert_path: Path, http_path: Path, output_path: Path) -> None:
    cert = json.loads(cert_path.read_text(encoding="utf-8"))
    http = json.loads(http_path.read_text(encoding="utf-8"))
    actual = cert["actual"]
    bench = cert["benchmark"]
    latency = bench["latency_ms"]

    content = textwrap.dedent(
        f"""
        # One Piece Search V2 Certification

        **Status: CERTIFIED**

        Generated by the reproducible `Certify One Piece Search V2` GitHub Actions gate against Neon.

        ## Canonical catalog/search evidence

        - Logical Cards: **{actual['cards']}**
        - Physical Prints: **{actual['prints']}**
        - Card Search Profiles: **{actual['card_profiles']}**
        - Print Search Profiles: **{actual['print_profiles']}**
        - Active facets: **{actual['active_facets']}**
        - Duplicate print keys: **{actual['duplicate_print_keys']}**
        - Prints without a recorded image row: **{actual['missing_print_images']}**

        ## Search quality gate

        - Benchmark cases: **{bench['case_count']}**
        - Hard gates: **{bench['hard_gate']['passed']}/{bench['hard_gate']['total']}**
        - Soft quality: **{bench['soft_quality']['passed']}/{bench['soft_quality']['total']}**
        - Median query latency (GitHub runner → Neon): **{latency['median']} ms**
        - P95: **{latency['p95']} ms**
        - Maximum: **{latency['max']} ms**

        Covered behavior includes canonical names, exact collectors, compound queries, typo tolerance, structured color/type/language/rarity intent, exact numeric stats, ranges and comparators.

        ## Full-stack HTTP gate

        - Exact collector singleton: **PASS**
        - Typo ranking: **PASS** (`{http['typo_top']}`)
        - Natural numeric range: **PASS**
        - Compound name + numeric range: **PASS**
        - Advanced Print search: **PASS**
        - Build contract: **{http['build_contract']}**
        - Image proxy: **HTTP {http['image_proxy']['status']} / {http['image_proxy']['content_type']}**

        ## UX contract

        - Normal Search groups physical variants into logical Cards.
        - Normal Search starts with 24 relevance-ranked Cards and can progressively load up to 96.
        - Advanced Search is exhaustive at Print level and paginated 24 per page.
        - Advanced filters are shareable/restorable through URL state.
        - Quick Filters expose Color, Card Type, Promo, SP and Treasure Rare without opening the full panel.
        - Full Advanced Search is ordered Identity → Card → Collecting.

        ## Intentionally deferred facets

        `Manga` and `Illustration Type` remain hidden until their print-level classification is sufficiently trustworthy. They are not part of the certified filter surface yet.

        ## Scope

        This certification covers the `catalog-v2` One Piece catalog/search stack, its production build contract and Neon data. Railway deploys the connected branch automatically and is treated as the deployment target; no manual Railway step is required for this repository gate.
        """
    ).strip() + chr(10)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cert", required=True, type=Path)
    parser.add_argument("--http", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    render(args.cert, args.http, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
